Public Class ShowInfo
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

    End Sub

    Protected Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Panel1.Visible = True
    End Sub

    Protected Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        SqlDataSource1.Insert()
        GridView2.DataBind()
        TextBox1.Text = ""
        TextBox3.Text = ""
        TextBox3.Text = ""
        Panel1.Visible = False
    End Sub

    Protected Sub SqlDataSource2_Selecting(sender As Object, e As SqlDataSourceSelectingEventArgs) Handles SqlDataSource2.Selecting

    End Sub

    Protected Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
        TextBox1.Text = ""
        TextBox3.Text = ""
        TextBox3.Text = ""
        Panel1.Visible = False
    End Sub

    Protected Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
        Panel2.Visible = True
    End Sub

    Protected Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
        SqlDataSource3.Insert()
        GridView2.DataBind()
        TextBox4.Text = ""
        TextBox5.Text = ""
        TextBox6.Text = ""
        Panel2.Visible = False
    End Sub

    Protected Sub Button6_Click(sender As Object, e As EventArgs) Handles Button6.Click
        TextBox4.Text = ""
        TextBox5.Text = ""
        TextBox6.Text = ""
        Panel2.Visible = False
    End Sub

    Protected Sub SqlDataSource1_Selecting(sender As Object, e As SqlDataSourceSelectingEventArgs) Handles SqlDataSource1.Selecting

    End Sub

    Protected Sub Button7_Click(sender As Object, e As EventArgs) Handles Button7.Click
        If Button7.Text = "Редактировать заказы" Then
            GridView2.AutoGenerateEditButton = True
            Button7.Text = "Закончить редактирование"
        Else
            GridView2.AutoGenerateEditButton = False
            Button7.Text = "Редактировать заказы"
        End If
    End Sub

    Protected Sub Button8_Click(sender As Object, e As EventArgs) Handles Button8.Click
        If Button8.Text = "Редактировать Заказчика" Then
            GridView1.AutoGenerateEditButton = True
            Button8.Text = "Закончить редактирование"
        Else
            GridView1.AutoGenerateEditButton = False
            Button8.Text = "Редактировать Заказчика"
        End If
    End Sub

    Protected Sub Button10_Click(sender As Object, e As EventArgs) Handles Button10.Click
        If Button10.Text = "Удалить Заказчика" Then
            GridView1.AutoGenerateDeleteButton = True
            Button10.Text = "Закончить удаление"
        Else
            GridView1.AutoGenerateDeleteButton = False
            Button10.Text = "Удалить Заказчика"
        End If
    End Sub

    Protected Sub Button9_Click(sender As Object, e As EventArgs) Handles Button9.Click
        If Button9.Text = "Удалить заказ" Then
            GridView2.AutoGenerateDeleteButton = True
            Button9.Text = "Закончить удаление"
        Else
            GridView2.AutoGenerateDeleteButton = False
            Button9.Text = "Удалить заказ"
        End If
    End Sub
End Class